{% set version = "0.2.1" %}

package:
  name: agate-dbf
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/agate-dbf/agate-dbf-{{ version }}.tar.gz
  sha256: 00c93c498ec9a04cc587bf63dd7340e67e2541f0df4c9a7259d7cb3dd4ce372f

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - agate >=1.5.0
    - dbfread >=2.0.5

  run:
    - python
    - agate >=1.5.0
    - dbfread >=2.0.5

test:
  imports:
    - agatedbf

about:
  home: http://agate-dbf.readthedocs.org/
  license: MIT
  license_family: MIT
  # license_file: COPYING - No manifest - see https://github.com/wireservice/agate-dbf/pull/3
  summary: 'agate-dbf adds read support for dbf files to agate.'
  doc_url: http://agate-dbf.readthedocs.org/
  dev_url: https://github.com/wireservice/agate-dbf

extra:
  recipe-maintainers:
    - pmlandwehr
