{% set name = "agate-dbf" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 6554828b10048a76dbb5bc4eff8911e059ea2b47155b7a89351e382915ca16fc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - agate >=1.5.0
    - dbfread >=2.0.5
    - setuptools
  run:
    - python >={{ python_min }}
    - agate >=1.5.0
    - dbfread >=2.0.5

test:
  imports:
    - agatedbf
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://agate-dbf.readthedocs.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: 'agate-dbf adds read support for dbf files to agate.'
  doc_url: http://agate-dbf.readthedocs.org/
  dev_url: https://github.com/wireservice/agate-dbf

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
