schema_version: 1

context:
  name: agate-dbf
  version: "0.2.4"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 6554828b10048a76dbb5bc4eff8911e059ea2b47155b7a89351e382915ca16fc

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - agate >=1.5.0
    - dbfread >=2.0.5
    - setuptools
  run:
    - python >=${{ python_min }}
    - agate >=1.5.0
    - dbfread >=2.0.5

tests:
  - python:
      imports:
        - agatedbf
      pip_check: true
      python_version:
        - ${{ python_min }}
        - "*"

about:
  license: MIT
  license_file: COPYING
  summary: agate-dbf adds read support for dbf files to agate.
  homepage: http://agate-dbf.readthedocs.org/
  repository: https://github.com/wireservice/agate-dbf
  documentation: http://agate-dbf.readthedocs.org/

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
